blog:
  pattern:              /blog
  defaults:             { _controller: BlogBundle:Blog:index }
  requirements:
    _method:            GET

blog_show:
  pattern:              /blog/{blog_id}
  defaults:             { _controller: BlogBundle:Blog:show }
  requirements:   
    blog_id:            "[[:digit:]]+"
    _method:            GET

blog_show_createComment:
  pattern:              /blog/{blog_id}
  defaults:             { _controller: BlogBundle:Blog:show }
  requirements:   
    blog_id:            "[[:digit:]]+"
    _method:            POST

blog_new:
  pattern:              /blog/new
  defaults:             { _controller: BlogBundle:Blog:create }
  requirements:
    _method:            GET

blog_create:
  pattern:              /blog
  defaults:             { _controller: BlogBundle:Blog:create }
  requirements:
    _method:            POST

blog_edit:
  pattern:              /blog/{blog_id}/edit
  defaults:             { _controller: BlogBundle:Blog:update }
  requirements:
    blog_id:            "[[:digit:]]+"
    _method:            GET

blog_update:
  pattern:              /blog/{blog_id}
  defaults:             { _controller: BlogBundle:Blog:update }
  requirements:
    blog_id:            "[[:digit:]]+"
    _method:            POST

blog_delete:
  pattern:              /blog/{blog_id}
  defaults:             { _controller: BlogBundle:Blog:delete }
  requirements:
    blog_id:            "[[:digit:]]+"
    _method:            DELETE
