<?php

namespace imag\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends EntityRepository
{
  public function getBlogs()
  {
    $q = $this->createQueryBuilder('b')
      ->select('b, bc')
      ->leftJoin('b.blogComments', 'bc')
      ->getQuery();

    return $q->getResult();
  }
}