<?php

namespace imag\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogCommentRepository extends EntityRepository
{
  public function getComments($blog_id)
  {
    $q = $this->createQueryBuilder('bc')
      ->select('b, bc')
      ->leftJoin('bc.blog', 'b')
      ->where('bc.blog = ?1')
      ->setParameter(1, $blog_id)
      ->getQuery();

    return $q->getResult();
  }
}